[package]
name = "arc"
version = "0.1.0"
authors = ["Constanza Aceves Rodriguez <cacevesr@u.rochester.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
uuid = { version = "0.8", features = ["serde", "v4", "v5"] }
=======
clap = "3.0.0-beta.2"
uuid = { version = "0.8", features = ["v4", "v5"] }
>>>>>>> 57d90166a3571faf2415c167b9577fe04d1ecd60
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
diffy = "0.2"
